apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
      - name: myapp-frontend
        image: amirsh2023/myapp-frontend:1.0.0  # Update this when you push a new version
        ports:
        - containerPort: 3000  # Assuming your frontend runs on port 3000
